name = "weathergripe"
main = "src/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Production environment variables
[vars]
DOMAIN = "weather.gripe"
ADMIN_EMAIL = "admin@weather.gripe"
USER_AGENT = "weather.gripe/1.0 (https://weather.gripe; admin@weather.gripe)"
NOMINATIM_URL = "https://nominatim.openstreetmap.org"
NWS_API_URL = "https://api.weather.gov"

# KV Namespace bindings for persistent state only
# Weather and location data use Cache API instead
[[kv_namespaces]]
binding = "FOLLOWERS"
id = "231e3ac502bd4fa1a60334662f253b8d"
preview_id = "231e3ac502bd4fa1a60334662f253b8d"

[[kv_namespaces]]
binding = "POSTS"
id = "7ac48a8ed5b846f9ba1fbf0d3abb66a3"
preview_id = "7ac48a8ed5b846f9ba1fbf0d3abb66a3"

[[kv_namespaces]]
binding = "ALERTS"
id = "054f2d2785d142efbf9177ed861fb9eb"
preview_id = "054f2d2785d142efbf9177ed861fb9eb"

[[kv_namespaces]]
binding = "DELIVERY_QUEUE"
id = "ad4a3a45756143c8a527b34929dd717d"
preview_id = "ad4a3a45756143c8a527b34929dd717d"

[[kv_namespaces]]
binding = "KEYS"
id = "7810c66d6ef84993a962186b95df5311"
preview_id = "7810c66d6ef84993a962186b95df5311"

# Cron triggers for scheduled posts and alert monitoring
[triggers]
crons = [
  "*/5 * * * *"  # Run every 5 minutes for severe weather alerts and hourly posts
]

# Staging environment
[env.staging]
name = "weather-gripe-staging"
vars = { DOMAIN = "staging.weather.gripe", ENVIRONMENT = "staging" }

[[env.staging.kv_namespaces]]
binding = "FOLLOWERS"
id = "231e3ac502bd4fa1a60334662f253b8d"

[[env.staging.kv_namespaces]]
binding = "POSTS"
id = "7ac48a8ed5b846f9ba1fbf0d3abb66a3"

[[env.staging.kv_namespaces]]
binding = "ALERTS"
id = "054f2d2785d142efbf9177ed861fb9eb"

[[env.staging.kv_namespaces]]
binding = "DELIVERY_QUEUE"
id = "ad4a3a45756143c8a527b34929dd717d"

[[env.staging.kv_namespaces]]
binding = "KEYS"
id = "7810c66d6ef84993a962186b95df5311"